### PR TITLE
feat!: Add support for user_data_replace_on_change, and updated AWS provider to v4.7+

### PR DESCRIPTION
**Pull request by brad-alexander**
## Description
Add support for [user_data_replace_on_change](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change) attribute

## Motivation and Context
Update to match aws provider feature

## Breaking Changes
I don't believe so, it only adds a bool var with default set to aws provider default.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Please update `versions.tf` to use AWS provider 4.7 as the minimum requirement in root module and in the examples. This PR will produce a major release.

**Review by antonbabenko — APPROVED** [review]
~Could you fix the failed checks (run `pre-commit run -a` and commit the changes locally) and I will merge this?~

I have fixed it for you. :)

**Comment by antonbabenko** [comment]
This PR is included in version 4.0.0 :tada:

**Comment by brad-alexander** [comment]
> I have fixed it for you. :)

Thank you! I appreciate all the help on this 🙏

**Pull request merged**
