### PR TITLE
feat: Add support for "metadata_options" argument

### PR DESCRIPTION
**Pull request by jeremyciak**
## Description

Adding support for the `metadata_options` argument of the `aws_instance` resource

## Motivation and Context

#191

### CODE REVIEW

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Looks good, but I have just a couple of comments.

This addition is not backward compatible with the existing code because it will trigger an update for users who don't specify `var.metadata_options`.

Could you please update the code to support it (using `dynamic` block)?

Could you also change from `c5.large` to something much smaller, so that it is not very $$$ to run in automation?

**Comment by jeremyciak** [comment]
@antonbabenko please let me know if the latest commit gets this to where you want it to be.

**Comment by jeremyciak** [comment]
I like your implementation a lot more... I modeled mine after the `root_block_device` which could probably more appropriately be implemented the same way you've done here. However making that change now would probably break implementations of this module "out in the wild".

**Comment by antonbabenko** [comment]
Yes, the original implementation was created in pre-0.12 times and I don't want to break it for existing features.

[v2.16.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v2.16.0) has been just released.

**Comment by yi2020** [comment]
@antonbabenko I played around with the new version (thank you) and noticed something odd:
After creating an instance with the module, if you add or remove the metadata_options, Terraform doesn't see that as a result to rebuild the instance.

**Pull request merged**
