### PR TITLE
Added support for CPU credits

### LINKED ISSUE #31: Support credit_specification option for T2.Unlimited instance types
Support for T2.Unlimited was added to the aws_instance resource with block:

credit_specification {
    cpu_credits = "unlimited"
  }

as per https://www.terraform.io/docs/providers/aws/r/instance.html#credit-specification
would be good to add this to your module?

### PR DESCRIPTION
**Pull request by antonbabenko**
Closes #31

### CODE REVIEW

**Comment by suizman** [comment]
Hi @antonbabenko  it seams that this option breaks the compatibility with other instance types.

```
Error: Error applying plan:

1 error(s) occurred:

* module.ec2.aws_instance.this: 1 error(s) occurred:

* aws_instance.this: Error launching source instance: InstanceCreditSpecification.NotSupported: The m4.2xlarge instance type does not support T2 Unlimited.
```

 Is there anyway to work around this without modifying the module?

**Comment by antonbabenko** [comment]
`cpu_credits` should be set only for T2 types of instances.

**Comment by antonbabenko** [comment]
Hmm, this is a nasty surprise :-/ I will release a fix soon.

**Comment by suizman** [comment]
Okis, thanks!
The current workaround I've found is to bring up some t2.$size instance and then choose another size and run terraform apply again. It's not a big deal..

**Comment by antonbabenko** [comment]
[v1.9.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v1.9.0) has been released.

**Comment by suizman** [comment]
Perfect! I've just tested the changes and they work as expected. Thanks @antonbabenko

**Pull request merged**
