### PR TITLE
feat: Add example for connecting via Session Manager without Internet access

### PR DESCRIPTION
**Pull request by luigidifraiawork**
## Description
Add an example demonstrating how an EC2 instance not connected to the Internet can be accessed using Session Manager through VPC Endpoints.

## Motivation and Context
I thought to provide the open-source community with a working example for the above-mentioned scenario.

## Breaking Changes
None.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by luigidifraiawork** [comment]
@antonbabenko Is there anything I can help with in order to facilitate a review of this pull request, please? I am happy to keep rebasing it in the meantime.

**Review by bryantbiggs — APPROVED** [review]
awesome, thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 5.5.0 :tada:

**Comment by luigidifraiawork** [comment]
> awesome, thank you!

You're welcome. Thank you for reviewing, approving and making this example part of the module.

**Pull request merged**
