### PR TITLE
BREAKING CHANGE: update module to include latest features and remove use of `count` for module `count`/`for_each`

### LINKED ISSUE #160: Support for multiple IPv4 addresses
Similar to the aws ec2 assign-private-ip-addresses (https://docs.aws.amazon.com/cli/latest/reference/ec2/assign-private-ip-addresses.html) add suport for multiple private IPv4 addresses in a single NIC.

I am curious why it is supported in ipv6 and not in ipv4.

Thanks.

### LINKED ISSUE #173: Add support for instance Hibernation configuration
In the module I can find the implementation of the instance_initiated_shutdown_behavior attribute.
However this of course only allows me to set what I would expect it to and has no impact on whether or not hibernation is possible.
This would be set via AWS Console using the checkbox **Stop - Hibernation** 
[Hibrnate Feature](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/Hibernate.html)

Since it is considered best practice to allow instances based on spot purchases to run with this option checked, I figured this would be a necessity to allow me easily bring up an instance in a spot instance purchase

### LINKED ISSUE #188: When specifying an ENI, the module breaks
This is something I don't honestly know how to fix in a generic way, but this module breaks when specifying an ENI. The only way to fix is to remove line 27 in `main.tf`. Maybe have two versions where one is instantiated of the ENI is defined and one that is instantiated if the ENI is not defined.

```
Error: ConflictsWith

  on .terraform/modules/myserv er/main.tf line 5, in resource "aws_instance" "this":
   5: resource "aws_instance" "this" {

"network_interface": conflicts with associate_public_ip_address
```

### LINKED ISSUE #213: Support timeouts block
## Is your request related to a new offering from AWS?
It exists: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance

## Describe the solution you'd like.
Add the ability to define custom timeouts shown in the above link.

Thanks.

### LINKED ISSUE #230: Support host_id
Currently, the module doesn't support `host_id`, this makes it impossible to use with macOS instances since they require a dedicated host.

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- update module to include latest features and remove use of `count` for module `count`/`for_each`
- `basic` example renamed to `complete` - no longer just basic and shows multiple examples for more of a complete setup
### New attributes added 
- `hibernation` 
- `secondary_private_ips`
- `capacity_reservation_specification`
- `launch_template`
- `enclave_options`
- `host_id`
- `timeouts`

### Removed variables
- `instance_count`
- `subnet_ids`
- `private_ips`
- `use_num_suffix`
- `num_suffix_format`

### Renamed outputs
- :info: All outputs used to be lists, and are now singular outputs due to the removal of `count`

### Removed Outputs
- `availability_zone`
- `placement_group`
- `key_name`
- `ipv6_addresses`
- `private_ip`
- `security_groups`
- `vpc_security_group_ids`
- `subnet_id`
- `credit_specification`
- `metadata_options`
- `root_block_device_volume_ids`
- `ebs_block_device_volume_ids`
- `volume_tags`
- `instance_count`

## Motivation and Context
- with the introduction of module level `count` and `for_each`, this means users can create as many ec2 instances as necessary with the module as opposed to the module itself trying to control how many instances are created. in addition, the use of `for_each` is preferred to avoid disruptive updates that can be encountered when using count and modifying one of the resources within the list

Closes #92
Closes #160
Closes #173
Closes #188
Closes #213
Closes #230

## Breaking Changes
- Yes, see `UPGRADE-3.0.md` for upgrade instructions

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
	- examples updated and validated for new changes

### CODE REVIEW

**Comment by firke** [comment]
hey @bryantbiggs  @antonbabenko, thank you for your work on this! Quick question in regards to this release - what was the reasoning behind removing some of the outputs, e.g. availability_zone/private_ip?

**Comment by antonbabenko** [comment]
The main reason for that is that those attributes (outputs) are not in the resource itself (see [aws_instance docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#attributes-reference)).

We probably had them in the past but they were actually arguments (inputs).

**Comment by firke** [comment]
@antonbabenko so I think Hashicorp have changed layout of docs a little, and outputs block does not explicitly mention all of the outputs, as it also includes inputs as part of outputs. This is listed in outputs part of docs:
`In addition to all arguments above, the following attributes are exported`
This would include private_ip as part of output.

I've tested it with a forked version - https://github.com/firke/terraform-aws-ec2-instance
Only private_ip output was added as part of test. Once used, private_ip attribute was available to other resources, route53 record as an example:
```
resource "aws_route53_record" "private_dns" {
  zone_id = data.terraform_remote_state.network.outputs.private_zone_id
  name    = "rpc"
  type    = "A"
  ttl     = "300"
  records = [module.ec2.private_ip]
}
```

**Comment by firke** [comment]
Ah, I see, this clicked with me just recently about the docs. So using same example of private_ip, referencing which should be a trivial task, my understanding is just now without these outputs it's not possible, and if these are not returned will either need to use forked version or use a data source for an ec2_instance object? Sorry if I've missed something. :)

**Comment by antonbabenko** [comment]
You're right about using the [data-source `aws_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instance) as a fetcher for the data you need based on EC2 instance id.

**Comment by suppix** [comment]
@antonbabenko Looks like it's not so handy, especially to use this module with terragrunt.

**Comment by antonbabenko** [comment]
This module creates an EC2 instance so that it is possible to get some more information about the resource using data source in other places. In terragrunt you can use `generate` block to create _extra data-source code_ or make a small module that will act as a fetcher/bridge.

**Pull request merged**
