### PR TITLE
feat: Add support for `disable_api_stop` attribute

### PR DESCRIPTION
**Pull request by msharma24**
## Description
Added disable_api_stop action attribute to the ec2 instance resource - Supported in latest TF Provider release [4.20.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4200-june-23-2022)

## Motivation and Context
 To prevent your instance from being accidentally stopped, you can enable stop protection for the instance. 

## Breaking Changes
No

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by msharma24** [comment]
@bryantbiggs  looks good ?

**Comment by bryantbiggs** [comment]
you have a failing CI check - you need to run `pre-commit run -a`

**Comment by msharma24** [comment]
@bryantbiggs  👍 

```
pre-commit run -a
Terraform fmt............................................................Passed
Terraform wrapper with for_each in module................................Passed
Terraform validate.......................................................Passed
Terraform docs...........................................................Passed
Terraform validate with tflint...........................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
```

**Review by bryantbiggs — APPROVED** [review]
Thanks @msharma24 !

**Comment by antonbabenko** [comment]
This PR is included in version 4.1.0 :tada:

**Pull request merged**
